services:
  db:
    image: postgres:13

    env_file:
      - .env

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - shared

  web:
    build: .
    command: gunicorn --config gunicorn_config.py event_planning.wsgi:application
    volumes:
      - .:/app
    expose:
      - 8001
    env_file:
      - .env

    depends_on:
      - db
    networks:
      - shared

networks:
  shared:
    external: true

volumes:
  postgres_data:
