services:
  db:
    image: postgres:13

    env_file:
      - .env

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - shared

  event-web:
    build: .
    command: gunicorn --config gunicorn_config.py event_planning.wsgi:application
    volumes:
      - .:/app

    env_file:
      - .env
    expose:
      - 8001
    depends_on:
      - db
    networks:
      - shared

networks:
  shared:
    external: true

volumes:
  postgres_data:
