# Generated by Django 5.1.2 on 2024-10-23 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_planning_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='medium',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='event_planning_api.medium'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='privacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_planning_api.privacy'),
        ),
    ]
