# Generated by Django 5.1.2 on 2024-10-23 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_planning_api', '0002_event_medium_alter_event_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='members',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='rsvp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event_planning_api.rsvp'),
        ),
    ]
