# Generated by Django 5.1.2 on 2024-10-23 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_planning_api', '0003_alter_event_members_alter_invitation_rsvp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='evnet',
            new_name='event',
        ),
    ]
