# Generated by Django 5.1.2 on 2024-10-31 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_planning_api', '0007_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='conditions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
